/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitMab;


        import  bitMab.bitmam.Bitmap;

        import java.io.IOException;


public class App {

    public static void main(String[] args) throws IOException {

        if (args.length > 1) {
            try {

            Bitmap BitMapOpject = new Bitmap(args[1],args[2]); //create bitmap opject

            if (args[0].equals("green")) {
                BitMapOpject.greenLayer();

            }
           else if (args[0].equals("suny")) {
                BitMapOpject.sunyColor();

            }

           else if (args[0].equals("purple")) {
                BitMapOpject.purpleLayer();

            }

            else {
                System.out.println("method is error");
            }


            // In terminal, the second argument refers to where you want the new bitmap to populate.

            BitMapOpject.ImageWrite(args[2]);}
            catch (Exception e){
                System.out.println("path is error");
            }

        }

        else {
            System.out.println("ERROR ENTER");
        }
    }
}
