/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitMab.bitmam;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws IOException {
        Bitmap classUnderTest = new Bitmap("test.bmp","non.bmp");
        assertEquals(classUnderTest.greenLayer(), 1);
    }
}
